CREATE TABLE BRANCH( BNAME VARCHAR(10), BCODE NUMERIC,  BCITY VARCHAR(10) );
ALTER TABLE BRANCH ADD PRIMARY KEY(BNAME);
CREATE TABLE STAT( SNAME VARCHAR(10),  BNAME VARCHAR(10), FOREIGN KEY(BNAME) REFERENCES BRANCH(BNAME)  );
CREATE TABLE SCHEME( SCHNO NUMERIC, DEPO NUMERIC, BENIFIT NUMERIC );
CREATE TABLE CUSTOMER( CNAME VARCHAR(10), CCITY VARCHAR(10),  CSEX VARCHAR(10) );
INSERT INTO BRANCH VALUES("JUI",003,"BIWANI"),("HANSI",009,"HISAR"),("LOHARU",008,"LOHARU"),("TOSHAM",007,"TOSHAM");
INSERT INTO customer VALUES("NITESH","BHIWANI","MALE"),("SHE","ROHTAK","FEMALE"),
("KAIRA","MUMBAI","FEMALE"),("SUBHAM","MUMBAI","MALE"),("SHEETAL","KOLKATA","FEMALE"),("SUMIT","KOLKATA","MALE");
INSERT INTO STAT VALUES("HARIYANA","JUI"),("HARIYANA","TOSHAM"),("PUNJAB","HANSI"),("UP","LOHARU");
INSERT INTO SCHEME VALUES(1,4000,200),(2,3000,400),(3,6000,1000),(4,900,120);

SELECT * FROM BRANCH;
SELECT * FROM CUSTOMER WHERE CCITY LIKE "%MUMBAI%";
SELECT * FROM CUSTOMER WHERE CSEX LIKE "MALE%" AND CCITY LIKE "%KOLKATA%";
SELECT SNAME ,COUNT(SNAME) FROM STAT  GROUP BY SNAME;
SELECT * FROM SCHEME;