CREATE TABLE STUDENT(
    SNAME VARCHAR(23),
    SUID VARCHAR(20),
    SDEPT VARCHAR(20),
    SDOB DATE,
    SEC NUMERIC,
    PRIMARY KEY(SUID)
);
CREATE TABLE COURSE(
    SCOURSE VARCHAR(20),
    SUID VARCHAR(20),
    FOREIGN KEY(SUID) REFERENCES STUDENT(SUID)
);
CREATE Table ATTANDENCE(
    SUID VARCHAR(20),
    TOTALATT NUMERIC,
    FOREIGN KEY(SUID) REFERENCES STUDENT(SUID)
)
CREATE TABLE CGPA(
    SUID VARCHAR(20),
    ACGPA NUMERIC,
    FOREIGN KEY(SUID) REFERENCES STUDENT(SUID)
)